<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testCases.CAUniCentre.ViewingQuickProfile" tests="1" time="3.783" ignored="9" failures="0" timestamp="21 Nov 2019 11:57:02 GMT" skipped="0" hostname="LAP06589" errors="1">
  <testcase name="ViewingQuickProfile" time="3.783" classname="testCases.CAUniCentre.ViewingQuickProfile">
    <error type="java.lang.RuntimeException" message="failed to login.">
      <![CDATA[java.lang.RuntimeException: failed to login.
	at alm.qc.restapi.MF_Assert.assertTrue(SourceFile:15)
	at alm.qc.restapi.Instances.loginBasicAuthentification(SourceFile:150)
	at alm.qc.restapi.Instances.connectionLogin(SourceFile:22)
	at alm.qc.restapi.ExternalTests.uploadTestRun(SourceFile:122)
	at resources.base.WebBase.QcExecution(WebBase.java:804)
	at resources.base.WebBase.switchtoFrame(WebBase.java:904)
	at components.Components.Viewing_Quick_profile(Components.java:112)
	at frameworkCore.ComponentDriver.Executekeywords(ComponentDriver.java:65)
	at testCases.CAUniCentre.ViewingQuickProfile.ViewingQuickProfile(ViewingQuickProfile.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- ViewingQuickProfile -->
  <testcase name="setup" classname="resources.base.WebBase">
    <skipped/>
  </testcase> <!-- setup -->
  <testcase name="setup" classname="resources.base.WebBase">
    <skipped/>
  </testcase> <!-- setup -->
  <testcase name="setup" classname="resources.base.WebBase">
    <skipped/>
  </testcase> <!-- setup -->
  <testcase name="setup" classname="resources.base.WebBase">
    <skipped/>
  </testcase> <!-- setup -->
  <testcase name="setup" classname="resources.base.WebBase">
    <skipped/>
  </testcase> <!-- setup -->
  <testcase name="setup" classname="resources.base.WebBase">
    <skipped/>
  </testcase> <!-- setup -->
  <testcase name="setup" classname="resources.base.WebBase">
    <skipped/>
  </testcase> <!-- setup -->
  <testcase name="setup" classname="resources.base.WebBase">
    <skipped/>
  </testcase> <!-- setup -->
  <testcase name="setup" classname="resources.base.WebBase">
    <skipped/>
  </testcase> <!-- setup -->
</testsuite> <!-- testCases.CAUniCentre.ViewingQuickProfile -->
